// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kxwqwwhvapmdefrsvjsb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt4d3F3d2h2YXBtZGVmcnN2anNiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc0NDM1NjksImV4cCI6MjA2MzAxOTU2OX0.ENylIyPIBwfCnvWGpGBIHXQWBnaCg7ZEJy2trDSRwdM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);